# Generated by Django 5.0.1 on 2024-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_ups', models.CharField(max_length=10000)),
                ('sit_ups', models.CharField(max_length=10000)),
                ('squads', models.CharField(max_length=10000)),
            ],
        ),
    ]
