# Generated by Django 5.0.1 on 2024-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_push_sit_squad_delete_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='today_total',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='sit',
            name='today_total',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='squad',
            name='today_total',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
