# Generated by Django 5.0.1 on 2024-02-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_push_today_total_sit_today_total_squad_today_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_total', models.CharField(default=0, max_length=1000)),
                ('current_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=0, max_length=20)),
                ('total', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Push',
        ),
        migrations.DeleteModel(
            name='Sit',
        ),
        migrations.DeleteModel(
            name='Squad',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='main.records'),
        ),
    ]
